FROM plugins/base:linux-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Git Action" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache ca-certificates git openssh curl perl

ADD release/linux/amd64/drone-git-action /bin/
ENTRYPOINT ["/bin/drone-git-action"]
